ln -s $1/vendor ./system/vendor -f
ln -s $1/system/framework/boot.vdex ./system/framework/arm64/boot.vdex -f
ln -s $1/system/framework/boot-android.hidl.manager-V1.0-java.vdex ./system/framework/arm64/boot-android.hidl.manager-V1.0-java.vdex -f
ln -s $1/system/framework/boot-framework-oahl-backward-compatibility.vdex ./system/framework/arm64/boot-framework-oahl-backward-compatibility.vdex -f
ln -s $1/system/framework/boot-android.hidl.base-V1.0-java.vdex ./system/framework/arm64/boot-android.hidl.base-V1.0-java.vdex -f
ln -s $1/system/framework/boot-framework.vdex ./system/framework/arm64/boot-framework.vdex -f
ln -s $1/system/framework/boot-ext.vdex ./system/framework/arm64/boot-ext.vdex -f
ln -s $1/system/framework/boot-conscrypt.vdex ./system/framework/arm64/boot-conscrypt.vdex -f
ln -s $1/system/framework/boot-telephony-common.vdex ./system/framework/arm64/boot-telephony-common.vdex -f
ln -s $1/system/framework/boot-apache-xml.vdex ./system/framework/arm64/boot-apache-xml.vdex -f
ln -s $1/system/framework/boot-ims-common.vdex ./system/framework/arm64/boot-ims-common.vdex -f
ln -s $1/system/framework/boot-bouncycastle.vdex ./system/framework/arm64/boot-bouncycastle.vdex -f
ln -s $1/system/framework/boot-core-libart.vdex ./system/framework/arm64/boot-core-libart.vdex -f
ln -s $1/system/framework/boot-okhttp.vdex ./system/framework/arm64/boot-okhttp.vdex -f
ln -s $1/system/framework/boot-voip-common.vdex ./system/framework/arm64/boot-voip-common.vdex -f
ln -s $1/system/framework/boot-android.test.base.vdex ./system/framework/arm64/boot-android.test.base.vdex -f
ln -s $1/system/framework/boot.vdex ./system/framework/arm/boot.vdex -f
ln -s $1/system/framework/boot-android.test.base.vdex ./system/framework/arm/boot-android.test.base.vdex -f
ln -s $1/system/framework/boot-android.hidl.manager-V1.0-java.vdex ./system/framework/arm/boot-android.hidl.manager-V1.0-java.vdex -f
ln -s $1/system/framework/boot-android.hidl.base-V1.0-java.vdex ./system/framework/arm/boot-android.hidl.base-V1.0-java.vdex -f
ln -s $1/system/framework/boot-ims-common.vdex ./system/framework/arm/boot-ims-common.vdex -f
ln -s $1/system/framework/boot-voip-common.vdex ./system/framework/arm/boot-voip-common.vdex -f
ln -s $1/system/framework/boot-framework.vdex ./system/framework/arm/boot-framework.vdex -f
ln -s $1/system/framework/boot-telephony-common.vdex ./system/framework/arm/boot-telephony-common.vdex -f
ln -s $1/system/framework/boot-ext.vdex ./system/framework/arm/boot-ext.vdex -f
ln -s $1/system/framework/boot-apache-xml.vdex ./system/framework/arm/boot-apache-xml.vdex -f
ln -s $1/system/framework/boot-conscrypt.vdex ./system/framework/arm/boot-conscrypt.vdex -f
ln -s $1/system/framework/boot-core-libart.vdex ./system/framework/arm/boot-core-libart.vdex -f
ln -s $1/system/framework/boot-bouncycastle.vdex ./system/framework/arm/boot-bouncycastle.vdex -f
ln -s $1/system/framework/boot-okhttp.vdex ./system/framework/arm/boot-okhttp.vdex -f
ln -s $1/system/framework/boot-framework-oahl-backward-compatibility.vdex ./system/framework/arm/boot-framework-oahl-backward-compatibility.vdex -f
ln -s $1/system/lib64/libdefcontainer_jni.so ./system/priv-app/DefaultContainerService/lib/arm64/libdefcontainer_jni.so -f
ln -s $1/system/lib64/libprintspooler_jni.so ./system/app/PrintSpooler/lib/arm64/libprintspooler_jni.so -f
ln -s $1/system/lib64/libjni_pacprocessor.so ./system/app/PacProcessor/lib/arm64/libjni_pacprocessor.so -f
ln -s $1/system/lib64/libbluetooth_jni.so ./system/app/Bluetooth/lib/arm64/libbluetooth_jni.so -f
ln -s $1/system/lib64/libjni_jpegstream.so ./system/app/Gallery2/lib/arm64/libjni_jpegstream.so -f
ln -s $1/system/lib64/libjni_filtershow_filters.so ./system/app/Gallery2/lib/arm64/libjni_filtershow_filters.so -f
ln -s $1/system/lib64/libjni_eglfence.so ./system/app/Gallery2/lib/arm64/libjni_eglfence.so -f
ln -s $1/system/lib64/libjni_latinime.so ./system/app/LatinIME/lib/arm64/libjni_latinime.so -f
ln -s $1/system/lib64/libjni_tinyplanet.so ./system/app/Camera2/lib/arm64/libjni_tinyplanet.so -f
ln -s $1/system/lib64/libjni_jpegutil.so ./system/app/Camera2/lib/arm64/libjni_jpegutil.so -f
ln -s $1/system/lib64/libcups.so ./system/app/BuiltInPrintService/lib/arm64/libcups.so -f
ln -s $1/system/lib64/libwfds.so ./system/app/BuiltInPrintService/lib/arm64/libwfds.so -f
ln -s $1/system/lib64/libnfc_nci_jni.so ./system/app/NfcNci/lib/arm64/libnfc_nci_jni.so -f
ln -s $1/storage/self/primary ./sdcard -f
ln -s $1/system/product ./product -f
ln -s $1/vendor/odm/priv-app ./odm/priv-app -f
ln -s $1/vendor/odm/overlay ./odm/overlay -f
ln -s $1/vendor/odm/lib64 ./odm/lib64 -f
ln -s $1/vendor/odm/lib ./odm/lib -f
ln -s $1/vendor/odm/framework ./odm/framework -f
ln -s $1/vendor/odm/firmware ./odm/firmware -f
ln -s $1/vendor/odm/etc ./odm/etc -f
ln -s $1/vendor/odm/bin ./odm/bin -f
ln -s $1/vendor/odm/app ./odm/app -f
ln -s $1/system/etc ./etc -f
ln -s $1/vendor/lib/dsp ./dsp -f
ln -s $1/sys/kernel/debug ./d -f
ln -s $1/sbin/charger ./charger -f
ln -s $1/data/user_de/0/com.android.shell/files/bugreports ./bugreports -f
ln -s $1/system/bin ./bin -f
